### ISSUE TITLE
is.empty(null) returns false (should return true?)

### ISSUE THREAD

**Issue by dominicbarnes** [enricomarino/is#13]
I just noticed that `is.empty(null)` does not return `false` like I would expect. I'm thinking it should return `true`, is this a bug or an intentional decision?

**Comment by ljharb** [comment]
"empty" here is a fuzzy conceptual "empty". "not empty" means "is present" or "contains something" -wWhy would you expect `null` to indicate presence or contents?

**Comment by dominicbarnes** [comment]
That's what I'm saying, `is.empty(null) === false`, which means it thinks that `null` is somehow "empty". (which it's not)

**Comment by ljharb** [comment]
Ah, I misunderstood. That logic makes sense to me.

**Comment by dominicbarnes** [comment]
I just went ahead and opened a PR :P
