### ISSUE TITLE
v3.0.0 corrupted on npm?

### ISSUE THREAD

**Issue by dominicbarnes** [enricomarino/is#15]
I'm not sure if it's _just me_ or what, but I whenever I install `is`, it is missing `index.js`, so I keep getting the "can't find module 'is'" error.

Is anyone else experiencing this? I've cleared out every bit of npm cache I can think of, still getting the same result.

**Comment by dominicbarnes** [comment]
For what it's worth, I've downgraded to `is@2` and the problem appears to have gone away. I think something is up w/ `3.0.0`.

**Comment by ljharb** [comment]
Hmm, thanks for letting me know - I think this is an `npm` bug. I'll contact them to find out.

**Comment by ljharb** [comment]
Thanks - I've published `v3.0.1` and unpublished `v3.0.0` - this is an `npm` bug which sometimes affects publishing (https://github.com/npm/npm/issues/5082).
