### ISSUE TITLE
is.not?

### ISSUE THREAD

**Issue by dmazur** [enricomarino/is#20]
I wonder if implementing jasmine-like syntax sugar makes any sense. For example `is.not.object`. I can try and implement that if you would be interested in including such feature.

**Comment by ljharb** [comment]
To do that trivially would require using ES5 getters/setters, which are horrifically bad for a plethora of reasons.

We could invert all the methods on `is` and install them on `is.not = {}`, however.

I'm open to it but I'd want to see a sample implementation first.

**Comment by dmazur** [comment]
Sure, I'll get to it tomorrow. Thanks :)

**Comment by frank-dspeed** [comment]
maybe putting a ! in front of the is helper is enough?

**Comment by Karbashevskyi** [comment]
Hello, I don't know how it happened that I didn't find this package earlier, but I wrote my own without knowing that a similar one already exists :)

https://www.npmjs.com/package/@p4ck493/ts-is

<img width="753" alt="image" src="https://user-images.githubusercontent.com/31188317/211161561-a6bba04f-df91-4d03-99fe-ef6a7023b940.png">
