### ISSUE TITLE
is.number(NaN) returns true

### ISSUE THREAD

**Issue by watt** [enricomarino/is#26]
I realize that this is intentional, but I'm not sure how you can justify calling `NaN` a number when it is expressly designed to represent the concept of something that is _not a number_. This behavior defies expectations.

**Comment by ljharb** [comment]
`typeof NaN === 'number'`. This is how `NaN` works in JavaScript, and in IEEE 754, which is implemented by a number of languages.

If this defies your expectations, your expectations are flawed.

**Comment by watt** [comment]
I guess my expectations are flawed indeed, because I expected this to get closed immediately, but I didn't expect to be insulted.

**Comment by ljharb** [comment]
@watt I apologize if you feel insulted, that was not my intent. It seemed pretty clear that you were using this issue to vent your frustration with the IEEE 754 number standard, and that there wasn't anything actionable here, so I didn't see the need to be particularly gentle. I'll try to be more tactful in the future.

**Comment by watt** [comment]
Thank you. I wasn't actually aware that the reason for this had anything to do with the underlying implementation — it just surprised me because it seems so very wrong semantically.
