### ISSUE TITLE
BigInt support

### ISSUE THREAD

**Issue by theuves** [enricomarino/is#36]
Since May, Chrome has support for [BigInt](https://venturebeat.com/2018/05/29/chrome-67-arrives-with-generic-sensor-api-and-bigint-support/).

I think it would be interesting to have `is.bigint`, wouldn't it?

**Comment by ljharb** [comment]
Although I'd recommend using https://www.npmjs.com/package/is-bigint for that, it definitely should be added here as well. I'll do so shortly.
