### ISSUE TITLE
Maybe document is type chaining Union Types StringArray

### ISSUE THREAD

**Issue by frank-dspeed** [enricomarino/is#37]
```js
import * as is from 'is'
const isUnionStringArray = val => is.Array(val) || is.String(val);
isUnionStringArray(StringOrArray )//=> true
```

**Comment by ljharb** [comment]
I don’t think we need to document the basic programming mechanism of “or” or the basic javascript mechanism of “making a function”.

Separately, this package should be imported with `import is from ‘is’`; it only has a default export.

**Comment by frank-dspeed** [comment]
@ljharb but many issues are about how to do that.

**Comment by ljharb** [comment]
There's only 10 issues ever filed on this repo; only 1 of them is about more types in a general sense, and that's not about union types.
