### ISSUE TITLE
is Promise?

### ISSUE THREAD

**Issue by bleeinc** [enricomarino/is#38]
[from is-promise]
`function isPromise(obj) {
  return !!obj && (typeof obj === 'object' || typeof obj === 'function') && typeof obj.then === 'function';
}`

Considering this wonderful bit of mishap this lib seems to be a much better approach rather than bringing in a single lib like is-promise. 

https://www.reddit.com/r/javascript/comments/g83evc/createreactapp_breaks_due_to_dependency_on/

**Comment by ljharb** [comment]
That is a broken isPromise check - it’s an “is thenable” check. isPromise is `Promise.resolve(x) === x`, and it’s an antipattern to be checking if something is a promise (or a thenable, for that matter).

Single libs are a much better approach than bucket libs like this one; a bigger lib size makes problems *more* likely, not less.
