### ISSUE TITLE
is.equal get weird result for functions

### ISSUE THREAD

**Issue by ayqy** [enricomarino/is#40]
is.equal(alert, () => {})
true
is.equal(alert, Math.max)
true
is.equal(() => 1, () => 2)
true

**Comment by ayqy** [comment]
if (type === '[object Function]') {
  return value.prototype === other.prototype;
}

why did you compare prototype ? confusing..

**Comment by ljharb** [comment]
Any kind of comparison for functions is confusing, because they’re not comparable.

=== already compares identity, so this library chose to make sure they’re the same kind of function.

In other words, Math.max and an arrow function shouldn't be equal unless you’re transpiling (since arrow functions don’t have a prototype) - and an async function won’t be equal to a regular one.

**Comment by ayqy** [comment]
Agree with functions are not comparable, but just comparing their prototype attributes seems buggy from my test cases:

> Math.max and an arrow function shouldn't be equal unless you’re transpiling (since arrow functions don’t have a prototype) - and an async function won’t be equal to a regular one.

From a library maintainer's view, I think it's better to compare by === or ignore functions or pass a comparator from library user, anyway a buggy implementation is not so good, because it's not predictable at all. (Arrow functions made things worse)

**Comment by ljharb** [comment]
I don't see how it's not predictable - any two of the same kind of function will be `===`, any two of a different kind will not be.

**Comment by ayqy** [comment]
Ah ah, I could try to explain "predictable" more clearly:

predictable:
```
// any two function instances are not equal as we all known
function sum() {}
function handleButtonClick() {}
// what I say "predictable"
sum !== handleButtonClick
let sum_ = sum;
// what I say "predictable"
sum_ === sum;
```

not predictable:
```
// true?? why
is.equal(alert, () => {})

const fib = () => {}
async function asyncFib() {}
// true?? why
is.equal(fib, asyncFib)

// the above are what I say "not predictable", bcz it's incredible in the JavaScript world.
```

For classes(what you say "kind"), maybe comparing prototype is reasonable:

predictable:
```
class Dog {}
class Cat {}
function Button() {}
function Panel() {}
is.equal(Dog, Cat) === false
is.equal(Button, Panel) === false
// the above are what I say "predictable", which match our common sense.
```

*For non-classes, comparing prototype makes nonsense*, and I found these lines kept 10 years:

```
if (type === '[object Function]') {
return value.prototype === other.prototype;
}
```

so I issued to ask whether we need to specify the comparing behavior of arrow functions, async functions, generator functions and other new things... or we should compare non-classes functions by === to make non-classes compare more predictable ?

Regards :)

**Comment by ljharb** [comment]
If the semantics you want are to compare by identity, you should of course use `===` since that's what it's for.

We don't need to specify the comparing behavior for functions, because each kind of builtin function already has, by spec, its own `.prototype`.

**Comment by ayqy** [comment]
compare by identity is ok for direct function compare, but is.equal is more powerful for deep structure compare like:

```
const deepNestedObject = {
  // any deep nested structure as you can imagine
  a: (a, b) => a + b
};
const anotherDeepNestedObject = {
  // any deep nested structure as you can imagine
  a: (a, b) => a * b
};
// true??
is.equal(deepNestedObject, anotherDeepNestedObject)
```

what I predict is:
```
// exactly false, apparently
is.equal(deepNestedObject, anotherDeepNestedObject)
// or
is.equal(deepNestedObject, anotherDeepNestedObject)
throw Error('functions are not comparable')
// or
console.warn('functions are not comparable, function values maybe ignored')
```

Any kind of above behaviors is more reasonable than throw question marks to library user:
```
// true??
is.equal(deepNestedObject, anotherDeepNestedObject)
```

and then they dive into source to find the secret lines:
```
if (type === '[object Function]') {
return value.prototype === other.prototype;
}
```

**Comment by ljharb** [comment]
ah, I see what you're asking.

To be clear, this isn't about predictability - it's simply that the semantics you want aren't what this library has. "Predictable" means that it is possible to know with certainty what the result is - not that it matches your expectations or intuitions.

It seems you want to recursively compare two objects/arrays, but you want `===` semantics when functions are found instead of the current choice. I'm not sure how that's really possible to provide here without a breaking change. Have you tried https://npmjs.com/deep-equal or https://npmjs.com/is-equal ?

**Comment by ayqy** [comment]
😂 Simple lines from the top floor is intend to provide the minimal re-produce case, I forgot to attach my use case.

And as you said what I care about is the semantic match, equal means =, is.equal means arguments are =.

> I want === semantics when functions are found instead of the current choice.

You caught the point exactly!

So, non-breaking change maybe another comparator parameter like this:

```
is.equal(nested, anotherNested, (a, b, buildinCcomparator) => typeof a === 'function' ? a === b : buildinCcomparator(a, b))
```

Feel free to close the issue since you have got all my points.

**Comment by ljharb** [comment]
I think we can close it for now, but if more than one person wants this we can consider reopening it.
